<a href="https://colab.research.google.com/github/SanthoshReddy-5/Numpy_Tutorial/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array creation using python list and tuple**
**numpy.array( ) function**

In [16]:
#array creation
import numpy
#list
list1=[1,2,3,4,5]
print("list:",list1)
#tuple
tuple1=(6,7,8,9,10)
print("tuple:",tuple1)
arr1=numpy.array(list1)
arr2=numpy.array(tuple1)
print("array1:",arr1)
print("array2:",arr2)

list: [1, 2, 3, 4, 5]
tuple: (6, 7, 8, 9, 10)
array1: [1 2 3 4 5]
array2: [ 6  7  8  9 10]


**numpy.zeros( ) function**

In [17]:
#numpy.zeros()
import numpy as np
arr = np.zeros((2, 3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


**numpy.ones( ) function**

In [7]:

#numpy.ones() function
import numpy as np
arr = np.ones((2, 3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


**numpy.arange( ) function**

In [8]:

#numpy.arange() function
import numpy as np
arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


**numpy.linspace( ) function**

In [10]:

#numpy.linspace() function
import numpy as np
arr = np.linspace(0, 5, 3)
print(arr)
arr=np.array(arr,dtype=int)
print(arr)

[0.  2.5 5. ]
[0 2 5]


**numpy.reshape( ) function**

In [13]:

#numpy.reshape() function
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
reshaped_arr= np.reshape(a, (2, 3))
print(reshaped_arr)

[1 2 3 4 5 6]
[[1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
result = np.resize(a, (3, 3))
# result: array([[1, 2, 3],
#                [4, 1, 2],
#                [3, 4, 1]])
print(result)

[[1 2 3]
 [4 1 2]
 [3 4 1]]


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
result = np.dstack((a, b))
# result: array([[[ 1,  7],
#                 [ 2,  8],
#                 [ 3,  9]],
#                [[ 4, 10],
#                 [ 5, 11],
#                 [ 6, 12]]])
print (result)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
result = np.split(a, 3)
# result: [array([1, 2]), array([3, 4]), array([5, 6])]
print (result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = 2
result = a + b
# result: array([3, 4, 5])
print (result)

[3 4 5]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
result = a + b
# result: array([[11, 22, 33],
#                [14, 25, 36]])
print (result)

[[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
result = np.ravel(a)
# result: array([1, 2,
print ( result )

[1 2 3 4 5 6]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
result = a.flatten()
# result: array([1, 2, 3, 4, 5, 6])
print (result)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

a = np.array([[1], [2], [3]])  # Shape (3, 1)
b = np.array([10, 20, 30])     # Shape (3,)
result = a + b                 # Shape (3, 3) after broadcasting
# result: array([[11, 21, 31],
#                [12, 22, 32],
#                [13, 23, 33]])
print (result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])

# Adding a new axis to create a 2D array (row vector)
a_new = a[np.newaxis, :]
# a_new: array([[1, 2, 3]])

# Adding a new axis to create a 2D array (column vector)
a_new_col = a[:, np.newaxis]
# a_new_col: array([[1],
#                   [2],
#                   [3]])
print(a_new_col)

[[1]
 [2]
 [3]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])

# Adding a new axis to create a 2D array (row vector)
a_new = np.expand_dims(a, axis=0)
# a_new: array([[1, 2, 3]])

# Adding a new axis to create a 2D array (column vector)
a_new_col = np.expand_dims(a, axis=1)
# a_new_col: array([[1],
#                   [2],
#                   [3]])
print (a_new)
print(a_new_col)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [ ]:
import numpy as np
a = np.array([[[1, 2, 3]], [[4, 5, 6]]])
a_squeezed = np.squeeze(a)
print (a_squeezed)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
result = np.transpose(a)
# result: array([[1, 4],
#                [2, 5],
#                [3, 6]])
# Original shape: (2, 3), Transposed shape: (3, 2)
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
result = np.swapaxes(a, 0, 1)
# result: array([[[1, 2],
#                 [5, 6]],
#                [[3, 4],
#                 [7, 8]]])
# Swaps axis 0 and axis 1 of the original array
print (result)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
import numpy as np

data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean_axis1 = np.mean(data_2d, axis=1)
# mean_axis1: array([2., 5., 8.])
print(mean_axis1)

[2. 5. 8.]


In [ ]:
import numpy as np

data_1d = np.array([1, 2, 3, 4, 5])
mean_1d = np.mean(data_1d)
# mean_1d: 3.0
print(mean_1d)

3.0


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
std_dev = np.std(data)
# std_dev: 1.4142135623730951
print (std_dev)

1.4142135623730951


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
variance = np.var(data, axis=None)
# variance: 2.0
print (variance)

2.0


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
min_value = np.min(data)
# min_value: 1
print (min_value)

1


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
max_value = np.max(data)
# max_value: 5
print (max_value)

5


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(data)
# total_sum: 15
print(total_sum)

15


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
total_product = np.prod(data)
# total_product: 120
print (total_product)

120


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
percentile_50 = np.percentile(data, 50)
# percentile_50: 5.0
print(percentile_50)
percentiles_25_75 = np.percentile(data, [25,50,75,100])
# percentiles_25_75: array([3., 7.])
print (percentiles_25_75)


3.0
[2. 3. 4. 5.]


In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
correlation = np.corrcoef(x, y)
# correlation: array([[1., 1.],
#                     [1., 1.]])
print (correlation)

[[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Biased estimate and each column represents a variable
cov_combined = np.cov(data, bias=True, rowvar=False)
print("Biased Covariance Matrix with rowvar=False:")
print(cov_combined)
# Output:
# Biased Covariance Matrix with rowvar=False:
# [[6. 6. 6.]
#  [6. 6. 6.]
#  [6. 6. 6.]]

Biased Covariance Matrix with rowvar=False:
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [ ]:
import numpy as np

angles = np.array([0,45,90 ])
sine_values = np.sin(angles)
# sine_values: array([0., 1., 0.])
print (sine_values)
print(np.cos(angles))
print (np.tan(angles))




[0.         0.85090352 0.89399666]
[ 1.          0.52532199 -0.44807362]
[ 0.          1.61977519 -1.99520041]


In [ ]:
import numpy as np

values = np.array([0, 1, 2])
exp_values = np.exp(values)
# exp_values: array([ 1.        ,  2.71828183,  7.3890561 ])
print(exp_values)

[1.         2.71828183 7.3890561 ]


In [ ]:
import numpy as np

values = np.array([1, np.e, np.e**2])
log_values = np.log(values)
# log_values: array([0., 1., 2.])
print (log_values)

[0. 1. 2.]


In [ ]:
import numpy as np

# Dot product of 1D arrays (vectors)
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
dot_product = np.dot(vector_a, vector_b)
# dot_product: 32
print (dot_product)
# Dot product (matrix multiplication) of 2D arrays
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
dot_product_2d = np.dot(matrix_a, matrix_b)
# dot_product_2d: array([[19, 22],
#
print(dot_product_2d)

32
[[19 22]
 [43 50]]


In [ ]:
import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
outer_product = np.outer(vector_a, vector_b)
# outer_product: array([[ 4,  5,  6],
#                       [ 8, 10, 12],
#                       [12, 15, 18]])
print (outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
import numpy as np

# Inner product of 1D arrays (vectors)
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
inner_product = np.inner(vector_a, vector_b)
# inner_product: 32
print(inner_product)
# Inner product of 2D arrays
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
inner_product_2d = np.inner(matrix_a, matrix_b)
# inner_product_2d: array([[17, 23],
#                          [39, 53]])
print(inner_product_2d)

32
[[17 23]
 [39 53]]


In [ ]:
import numpy as np

# Coefficient matrix
A = np.array([[3, 1], [1, 2]])

# Ordinate values
B = np.array([9, 8])

# Solve for x
x = np.linalg.solve(A, B)
# x: array([2., 3.])
print(x)

[2. 3.]


In [ ]:
import numpy as np

# Square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the inverse
A_inv = np.linalg.inv(A)
# A_inv: array([[-2. ,  1. ],
#               [ 1.5, -0.5]])
print (A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np

# Square matrix
A = np.array([[1, 2], [3, 4]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
# eigenvalues: array([-0.37228132,  5.37228132])
# eigenvectors: array([[-0.82456484, -0.41597356],
#                      [ 0.56576746, -0.90937671]])
print (eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
import numpy as np

# Matrix to be decomposed
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, S, Vt = np.linalg.svd(A)
print("U:", U)
print("S:", S)
print("Vt:", Vt)
# Output:
# U: [[-0.2298477   0.88346102  0.40824829]
#     [-0.52474482  0.24078249 -0.81649658]
#     [-0.81964194 -0.40189603  0.40824829]]
# S: [9.52551809 0.51430058]
# Vt: [[-0.61962948 -0.78489445]
#      [-0.78489445  0.61962948]]




U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S: [9.52551809 0.51430058]
Vt: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
import numpy as np

# Symmetric, positive-definite matrix
A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

# Perform Cholesky decomposition
L = np.linalg.cholesky(A)
print("L:", L)
# Output:
# L: [[ 2.  0.  0.]
#     [ 6.  1.  0.]
#     [-8.  5.  3.]]

L: [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [ ]:
import numpy as np

# Generate a single random float
random_float = np.random.random()
print(random_float)
# Output: A single random float between 0.0 and 1.0

# Generate a 2x3 array of random floats
random_array = np.random.random((2, 2))
print(random_array)
# Output: A 2x3 array of random floats

0.93391020756702
[[0.76641785 0.20512356]
 [0.78963346 0.72882907]]


In [ ]:
import numpy as np

# Generate a single random sample from a uniform distribution
sample = np.random.uniform()
print(sample)

# Generate a 2x3 array of random samples from a uniform distribution between 10 and 20
samples = np.random.uniform(low=10.0, high=20.0, size=(2))
print(samples)

0.4660086472527343
[13.67394912 15.99222982]


In [ ]:
import numpy as np

# Generate a single random integer between 0 and 10
random_int = np.random.randint(0, 10)
print(random_int)
# Output: A single random integer between 0 and 9

# Generate a 2x3 array of random integers between 0 and 10
random_int_array = np.random.randint(0, 10, size=(2, 3))
print(random_int_array)
# Output: A 2x3 array of random integers between 0 and 9

9
[[4 9 1]
 [6 4 2]]


In [ ]:
import numpy as np

# Generate a single random choice from the array [1, 2, 3, 4, 5]
random_choice = np.random.choice([1, 2, 3, 4, 5])
print(random_choice)
# Output: A single random value from the array

# Generate a 2x3 array of random choices from the array [1, 2, 3, 4, 5]
random_choice_array = np.random.choice([1, 2, 3, 4, 5], size=(2, 3))
print(random_choice_array)
# Output: A 2x3 array of random choices from the array

4
[[4 2 5]
 [1 2 1]]


In [ ]:
import numpy as np

# Set the random seed to 42
np.random.seed(61)

# Generate a single random float
random_float = np.random.random()
print(random_float)
# Output: The same random float every time the seed is set to 42

# Generate a 2x3 array of random floats
random_array = np.random.random((2, 1))
print(random_array)
# Output: The same 2x3 array of random floats every time the seed is set to 42

0.8244694759132818
[[0.18134973]
 [0.87732677]]


In [ ]:
import numpy as np

# Generate a single random sample from a normal distribution
sample = np.random.normal()
print(sample)

# Generate a 2x3 array of random samples from a normal distribution with mean 5 and standard deviation 2
samples = np.random.normal(loc=5.0, scale=2.0, size=(2, 1))
print(samples)

-0.03550191085541864
[[ 2.18879587]
 [-0.28523715]]


In [ ]:
import numpy as np

# Generate a single random sample from a binomial distribution with 10 trials and probability of success 0.5
sample = np.random.binomial(n=10, p=0.5)
print(sample)

# Generate a 2x3 array of random samples from a binomial distribution with 20 trials and probability of success 0.3
samples = np.random.binomial(n=20, p=0.3, size=(2, 3))
print(samples)

6
[[ 4  6  5]
 [ 4 10  6]]
